Megatron-LM perf
Oneflow-Inc/DLPerf pull request #137
Opened 2021-05-11 03:33 UTC by ouyangyu

2021-05-12 07:40 UTC, ShawnXuan requested changes

2021-05-12 07:40 UTC, ShawnXuan commented on Megatron-LM/README.md
> +group | case | num-nodes | num-gpus-per-node | data-parallel-size | tensor-model-parallel-size | pipeline-model-parallel-size | micro-batch-size | micro-batch-size-times-data-parallel-size | num-accu
表格串列了
![image](https://user-images.githubusercontent.com/16327185/117937194-4c9f9780-b338-11eb-959d-59e1de7b646c.png)

2021-05-12 07:44 UTC, ShawnXuan commented on Megatron-LM/README.md
> +- ### 测试结果
下面表格也有问题。

2021-05-12 07:47 UTC, ShawnXuan commented
建议说明一下，显存记录可能不准确的问题。我们在测试中发现显存会在一些情况下上下跳动，而且megatron官方记录的显存和从nvidia-smi看到的显存不一致。

2021-05-12 08:17 UTC, ShawnXuan commented on Megatron-LM/README.md
> +# [NVIDIA](https://github.com/NVIDIA)/[Megatron-LM](https://github.com/NVIDIA/Megatron-LM)复现
`复现`改成`评测`比较好

2021-05-12 08:20 UTC, ShawnXuan commented on Megatron-LM/README.md
> +  本次测评提供了多组基于真实数据集的测试结果。测评基于[NVIDIA/Megatron-LM](https://github.com/NVIDIA/Megatron-LM).commit为`8aa4619f2b2a57b5725026a50ebd2b15e8121482`.基于以上，对Megatron-LM进行了从单卡到多机、从DP、MP、2D到PP等等的测试。
megatron包括BERT和GPT，这次我们只做了GPT，需要说明一下。

2021-05-17 06:18 UTC, ShawnXuan commented on Megatron-LM/README.md
> +group  |  case  |  lantency-  |  memory-
标题多了两个`-`

2021-05-18 03:08 UTC, leaves-zwx commented on Megatron-LM/README.md
> +  本次测评提供了多组基于真实数据集的测试结果。测评基于[NVIDIA/Megatron-LM](https://github.com/NVIDIA/Megatron-LM).commit为`8aa4619f2b2a57b5725026a50ebd2b15e8121482`.基于以上，对Megatron-LM下的GPT进行了从单卡到多机、从DP、MP、2D到PP等等的测试。
不是真实数据集吧？这个数据集就是我们自己做的数据集？我们没有用 megatron 那种方法做出来的数据集吧？

2021-05-18 03:09 UTC, leaves-zwx commented on Megatron-LM/README.md
> +  本次测评提供了多组基于真实数据集的测试结果。测评基于[NVIDIA/Megatron-LM](https://github.com/NVIDIA/Megatron-LM).commit为`8aa4619f2b2a57b5725026a50ebd2b15e8121482`.基于以上，对Megatron-LM下的GPT进行了从单卡到多机、从DP、MP、2D到PP等等的测试。
还有 DP、MP、2D 到 PP 换成全称吧，2D 是 OneFlow 里面的概念，Megatron 里面没有。

2021-05-18 03:10 UTC, leaves-zwx commented on Megatron-LM/README.md
> +  2020年OpenAI发布了GPT-3。于是在大规模模型的今天，训练超大规模模型所需的算力、存储已经不再是单机或几台机器能搞定的了，因此，对于如何解决分布式训练、如何能让大众也有能力搭建大规模模型都有着极高的挑战。基于此，NVIDIA提出了[Megatron-LM](https://github.com/NVIDIA/Megatron-LM)，基于PyTorch进行分布式训练GPT。
“搞定的了” 太口语化了

2021-05-18 03:16 UTC, leaves-zwx commented on Megatron-LM/README.md
> +  2020年OpenAI发布了GPT-3。于是在大规模模型的今天，训练超大规模模型所需的算力、存储已经不再是单机或几台机器能搞定的了，因此，对于如何解决分布式训练、如何能让大众也有能力搭建大规模模型都有着极高的挑战。基于此，NVIDIA提出了[Megatron-LM](https://github.com/NVIDIA/Megatron-LM)，基于PyTorch进行分布式训练GPT。
这里整句话的表述有些问题：1）"于是在大规模模型的今天"，“于是”是谁的承接？“今天”用大规模模型做定语？；2）“因此”后面与前面接不起来，因果关系应该是：单机或几台机器无法满足算力、存储需求 -> 需要分布式训练 -> 大规模模型的分布式训练对一般用户是极大挑战 -> Nvidia 基于 PyTorch 开发了 Megatron。

2021-05-18 03:43 UTC, leaves-zwx commented on Megatron-LM/README.md
> +  本次测评提供了多组基于真实数据集的测试结果。测评基于[NVIDIA/Megatron-LM](https://github.com/NVIDIA/Megatron-LM).commit为`8aa4619f2b2a57b5725026a50ebd2b15e8121482`.基于以上，对Megatron-LM下的GPT进行了从单卡到多机、从DP、MP、2D到PP等等的测试。
DP、MP、2D、PP 应该全全称，看文章的人可能并不知道这些简写，这个报告是给外面的人看的，不是给我们自己看的。2D 是 OneFlow 里面的术语，Megatron 里面没有这个概念吧？

2021-05-18 03:43 UTC, leaves-zwx commented on Megatron-LM/README.md
> +  2020年OpenAI发布了GPT-3。于是在大规模模型的今天，训练超大规模模型所需的算力、存储已经不再是单机或几台机器能搞定的了，因此，对于如何解决分布式训练、如何能让大众也有能力搭建大规模模型都有着极高的挑战。基于此，NVIDIA提出了[Megatron-LM](https://github.com/NVIDIA/Megatron-LM)，基于PyTorch进行分布式训练GPT。
“于是在大规模模型的今天” 中的 “于是” 没有上文，“大规模模型的今天” 这个也不是很通顺。

整句的承接关系不是很流畅。我觉得应该是：单机或几台机器无法满足大模型的算力、存储需求 -> 需要分布式训练 -> 大模型的分布式式训练对普通用户极有挑战 -> Nvidia 基于 PyTorch 实现了 Megatron。

2021-05-18 03:43 UTC, leaves-zwx commented on Megatron-LM/README.md
> +  测试对比Megatron-LM在各种情况下的内存使用率、速度等
谁与 Megatron-LM 对比？

2021-05-18 03:43 UTC, leaves-zwx commented on Megatron-LM/README.md
> +  根据官方[说明](https://github.com/NVIDIA/Megatron-LM#datasets)，从[OpenWebTextCorpus](https://skylion007.github.io/OpenWebTextCorpus/)下载数据集.
官方说明不是这样的，这个下载地址不是官方使用的数据集下载地址。这里可以直接引用 Megatron-LM 的数据集的制作说明。

2021-05-18 03:43 UTC, leaves-zwx commented on Megatron-LM/README.md
> +  根据官方[说明](https://github.com/NVIDIA/Megatron-LM#datasets)，从[OpenWebTextCorpus](https://skylion007.github.io/OpenWebTextCorpus/)下载数据集.
这里描述的数据集制作方式应该放在 OneFlow 那篇测试里面。

2021-05-18 03:43 UTC, leaves-zwx commented on Megatron-LM/README.md
> +  - NODE4=10.11.0.5
空行

2021-05-18 03:47 UTC, leaves-zwx commented on Megatron-LM/README.md
> +
https://github.com/Oneflow-Inc/OneTeam/blob/gpt/test/GPT/gpt_perf_mem.csv
这个测试结果也可以贴一下

2021-05-18 03:47 UTC, leaves-zwx commented on Megatron-LM/README.md
> +group |  case |  lantency |  memory |  Achieved teraFLOP/s per GPU |  Percentage of theoretical peak FLOP/s |  Achieved aggregate petaFLOP/s
这里的 memory 既然不对可以不贴出来。

2021-05-18 03:49 UTC, ouyangyu commented on Megatron-LM/README.md
> +  2020年OpenAI发布了GPT-3。于是在大规模模型的今天，训练超大规模模型所需的算力、存储已经不再是单机或几台机器能搞定的了，因此，对于如何解决分布式训练、如何能让大众也有能力搭建大规模模型都有着极高的挑战。基于此，NVIDIA提出了[Megatron-LM](https://github.com/NVIDIA/Megatron-LM)，基于PyTorch进行分布式训练GPT。
上文是2020发布了。。。

2021-05-18 03:59 UTC, leaves-zwx commented on Megatron-LM/README.md
> +    bash examples/mutil_perf_pretrain_gpt_dp_mp_pp.sh 8 1 8 512 4 10.11.0.2 0
这里的分别执行没说清楚，实际上最后的 0 要切换到 1, 2, ..., rank - 1

2021-05-18 03:59 UTC, leaves-zwx commented on Megatron-LM/scripts/create_dataset.sh
> +# Runs the "345M" parameter model
删除

2021-05-18 03:59 UTC, leaves-zwx commented on Megatron-LM/scripts/create_dataset.sh
> +WORLD_SIZE=1
这两行都删除

2021-05-18 03:59 UTC, leaves-zwx commented on Megatron-LM/scripts/mutil_perf_pretrain_gpt_dp_mp_pp.sh
> +# Runs the "345M" parameter model
删除

2021-05-18 03:59 UTC, leaves-zwx commented on Megatron-LM/README.md
> +    bash examples/mutil_perf_pretrain_gpt_dp_mp_pp.sh 8 1 8 512 4 10.11.0.2 0
这里的脚本运行示例并没有说清楚，如果要运行所有的 test case，用户到底要修改什么参数呢？这里要不把每种 case 的脚本都写个单独的文件。要不只写一个脚本，把所有参数定义成变量，然后用文字描述告诉用户怎么修改这些参数来跑各种 case。

2021-05-18 04:03 UTC, leaves-zwx commented on Megatron-LM/README.md
> +  2020年OpenAI发布了GPT-3。于是在大规模模型的今天，训练超大规模模型所需的算力、存储已经不再是单机或几台机器能搞定的了，因此，对于如何解决分布式训练、如何能让大众也有能力搭建大规模模型都有着极高的挑战。基于此，NVIDIA提出了[Megatron-LM](https://github.com/NVIDIA/Megatron-LM)，基于PyTorch进行分布式训练GPT。
“2020 年 OpenAI 发布了 GPT-3，开启了超大规模模型的时代。” 这样写是不是好一点？

2021-05-18 04:05 UTC, leaves-zwx commented on Megatron-LM/scripts/mutil_perf_pretrain_gpt_dp_mp_pp_1536_16_16.sh
> +# Runs the "345M" parameter model
删除

2021-05-18 07:42 UTC, chengtbf commented on Megatron-LM/README.md
> +
我也觉得可以把显存结果贴一下，然后在后面说明Megatron/PyTorch官方提供的内存信息可能不准确

2021-05-18 07:47 UTC, chengtbf commented
这个 PR 抓紧合并

2021-05-18 08:10 UTC, leaves-zwx commented on Megatron-LM/README.md
> +
讨论过后把这个结果贴在 OneFlow vs. Megatron GPT benchmark 报告里面

2021-05-18 08:16 UTC, leaves-zwx approved these changes

2021-05-18 08:18 UTC, merged