oneflow gpt dlperf report
Oneflow-Inc/DLPerf pull request #138
Opened 2021-05-12 06:21 UTC by ouyangyu

2021-05-12 06:23 UTC, yuanms2 commented on OneFlow/LanguageModeling/GPT/README.md
> +  - M_P=${1:-1}，`tensor-model-parallel-size`，指定了模型张量呗切分到多少个GPU设备上，即`张量模型并行度`
呗  --》 被

2021-05-12 08:01 UTC, ShawnXuan commented on OneFlow/LanguageModeling/GPT/reports/oneflow_gpt_report_0512.md
> +  所有日志都在`https://oneflow-public.oss-cn-beijing.aliyuncs.com/GPT/`下。
日志在两个不同的目录，需要合在一起或者说明一下。

2021-05-13 11:02 UTC, ShawnXuan requested changes

2021-05-13 11:02 UTC, ShawnXuan commented on OneFlow/LanguageModeling/GPT/reports/oneflow_gpt_report_0512.md
> +# OneFlow ResNet50-V1.5 Benchmark Test Report
wrong title. 
ResNet50-V1.5->GPT

2021-05-18 07:38 UTC, chengtbf commented on OneFlow/LanguageModeling/GPT/reports/oneflow_gpt_report_0512.md
> +- OneFlow Benchmark仓库版本: [master](https://github.com/Oneflow-Inc/OneFlow-Benchmark)
这个也最好用commit吧

2021-05-18 07:39 UTC, chengtbf commented
这个 PR 抓紧合并 @ouyangyu @ShawnXuan @leaves-zwx

2021-05-18 12:03 UTC, jackalcooper commented on OneFlow/LanguageModeling/GPT/README.md
> +在容器环境下运行测试可以帮助节省环境配置的时间。我们使用的容器镜像为 oneflow-manylinux2014-cuda11.2:0.1，可以根据 OneFlow 提供的 [dockerfile](https://github.com/Oneflow-Inc/oneflow/tree/master/docker/build) 来 build，或者直接[下载](https://oneflow-s
docker/package/manylinux/Dockerfile 是这个文件

2021-05-19 07:19 UTC, chengtbf approved these changes

2021-05-19 07:26 UTC, merged

2021-05-19 07:28 UTC, ShawnXuan approved these changes