Of wdl hugectr
Oneflow-Inc/DLPerf pull request #47
Opened 2020-09-06 16:19 UTC by ShawnXuan

HugeCTR Benchmark Test Scripts and Tools

2020-11-05 06:02 UTC, chengtbf commented
1. pull 一下最新的master

2. HugeCTR目录下
  - 官方仓库 https://github.com/NVIDIA/HugeCTR 有没有对应的实验数据供比对？
  - 没有提供实验复现的说明（scripts下只有脚本，但是没有提供如何复现的说明） 包括数据集制作、实验执行流程等
  - DLPerf/HugeCTR/reports/hugectr_test_4x8v100_report.md 里也有单机8卡的测试，为什么还需要分成两个报告文件？hugectr_test_8v100_report.md

3. OneFlow目录下
   - 这里的目录结构要改一下，有一个scripts的目录，然后还有一个 WDL_scripts 的目录？建议改成跟其他框架相同的目录，首级目录是框架名称，次级目录是对应的领域/模型，在对应的模型目录下的REAME里描述了复现流程和测试结果，目录下的scripts里包含测试使用的脚本。
   - 需要有复现流程
   - 需要有report的索引

4. 需要有W&D项目的对比报告，比较oneflow和HugeCTR的优劣及结论

2021-01-23 03:56 UTC, Flowingsun007 commented on HugeCTR/README.md
> +To show the tendency of the loss and AUC curves clearly, the total training batch size is set to 512, 512 is a small value compared to the WDL industry production scenario. Validation should be perfo
脚本和报告都比较齐全了，不过好像缺一个总体概述，包括这些实验的目的、结构；然后每个实验用例具体对应的脚本

2021-01-24 05:39 UTC, doombeaker commented
备忘一下，正式全面 review 前的工作还有：
1. fix batnch size 的图
2. 把 OneFlow 的单独测试报告改为英文版本（现在的是中文）
3. 把 HugeCTR/reports 目录下的 2 个单独的报告，合并为一份（有一份的deep size=16, OneFlow 没有对标实验，感觉可以删掉，仅用 deep size=32的那份即可）

2021-01-24 05:39 UTC, doombeaker commented
备忘一下，正式全面 review 前的工作还有：
1. fix batnch size 的图
2. 把 OneFlow 的单独测试报告改为英文版本（现在的是中文）
3. 把 HugeCTR/reports 目录下的 2 个单独的报告，合并为一份（有一份的deep size=16, OneFlow 没有对标实验，感觉可以删掉，仅用 deep size=32的那份即可）

2021-01-24 13:30 UTC, doombeaker commented on reports/dlperf_Wide_and_Deep_test_report_v1.md
> +|[HugeCTR](https://github.com/NVIDIA/HugeCTR)| 2.2 ||[samples/wdl](https://github.com/NVIDIA/HugeCTR/tree/v2.2/samples/wdl)|
这个地方，麻烦暄哥 @ShawnXuan 帮忙填一下 HugeCTR 的 docker 镜像信息，我不清楚。

2021-01-24 13:33 UTC, doombeaker commented
W&D 的 DLPerf 报告可以正式review了，还没有做的工作有：仓库首页的 README.md 也应该更新，加入 W&D 的介绍和链接。但是貌似需要大改才可以，而不是之前认为的“和原有的 DLPERF 并列”，比如，合并 W&D 时，原有的首页内容：
```
2 classical deep neural network models are tested in this repository, they are:

1. ResNet-50 v1.5
2. BERT-Base
```
以及相关的一系列测试参数介绍，其实都不适合 W&D ……

这个感觉要周reivew后讨论才能改。

2021-01-27 13:20 UTC, Flowingsun007 commented on HugeCTR/README.md
> +This test aims to show the training loss profile and validation area under the ROC Curve(AUC) during 300,000 steps testing. Compare to 500 iters test, we print loss and AUC every 1000 steps, it will
每一种类型的测试下应该加上复现所对应的脚本，以及必要的运行命令/参数说明(如果有的话)

2021-01-27 13:20 UTC, Flowingsun007 commented on HugeCTR/README.md
> +This test will keep the total batch size as a constant value(default is 16384), each test case adopts a different number of GPU devices, such as 1, 2, 4, 8, 16, 32.
同上

2021-01-27 13:22 UTC, Flowingsun007 commented on HugeCTR/README.md
> +This report summarized HugeCTR test on 4 nodes with 8 x Tesla V100 on Oct 2020.
缺乏一个总体概述，包括这些实验的目的、结构；不然给人乍一看的感觉是这么多实验，会很迷惑！

2021-01-27 13:26 UTC, Flowingsun007 commented on HugeCTR/scripts/vocab_x2_1_device_run.sh
> +done
很多.sh脚本末尾缺少blank line

2021-01-27 13:31 UTC, Flowingsun007 commented on reports/dlperf_Wide_and_Deep_test_report_v1.md
> +# DLPerf Wide & Deep Test Report V1.0
最好统一用小写譬如：dlperf_wide_and_deep_test_report_v1.md，大小写混用感觉比较奇怪；
另外，reports下最好根据模型新建文件夹，譬如reports/ClickThroughRate/WideDeepLearning或reports/HugeCTR

2021-01-27 14:01 UTC, Flowingsun007 commented on reports/dlperf_Wide_and_Deep_test_report_v1.md
> +## Test Environment
报告应该稍微详细些，需要包含简介、数据来源、背景介绍、评测指标和目的等类似的描述，可参考：https://github.com/Oneflow-Inc/DLPerf/blob/master/reports/dlperf_benchmark_test_report_v1_cn.md

2021-01-27 14:57 UTC, Flowingsun007 commented on reports/dlperf_Wide_and_Deep_test_report_v1_ch.md
> +所有的测试均在4台配置了8张Tesla V100-SXM2-16GB GPU显卡上进行，每台机器具体的硬件和软件配置描述如下：
所有的测试均在4台配置了8张Tesla V100-SXM2-16GB【的】GPU显卡上进行，每台机器具体的【软硬件】配置描述如下：

2021-01-27 15:03 UTC, Flowingsun007 commented on reports/dlperf_Wide_and_Deep_test_report_v1_ch.md
> +我们将看到当我们不断倍增vocab Size(词表大小)时，OneFlow的**Latency per Iteration**指标基本不发生改变这意味着几乎没有性能损失。
建议改成：我们将看到，当词表大小(vocab size)加倍递增时

2021-01-27 15:04 UTC, Flowingsun007 commented on reports/dlperf_Wide_and_Deep_test_report_v1_ch.md
> +# Wide & Deep 在深度学习框架上的性能测试报告V1.0
名称建议统一大小写，中文统一同cn表示(可改成：dlperf_wide_and_deep_test_report_v1_cn.md )

2021-01-28 06:45 UTC, doombeaker commented on reports/dlperf_Wide_and_Deep_test_report_v1.md
> +## Test Environment
好的，我参考 CNN/BERT 的补上

2021-01-28 15:35 UTC, doombeaker commented on reports/dlperf_Wide_and_Deep_test_report_v1.md
> +# DLPerf Wide & Deep Test Report V1.0
已经修改

2021-01-28 15:35 UTC, doombeaker commented on reports/dlperf_Wide_and_Deep_test_report_v1.md
> +## Test Environment
已补上

2021-01-29 02:18 UTC, Flowingsun007 commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1.md
> +The following is a summary of the **Vocab Size X2 Tests**. Other types testing results, including **Batch Size X2 Tests**, **Fixed Batch Size Tests**. Please refer to [OneFlow/ClickThroughRate/WideDe
此处，这两个link的链接打不开

2021-01-29 02:40 UTC, doombeaker commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1.md
> +The following is a summary of the **Vocab Size X2 Tests**. Other types testing results, including **Batch Size X2 Tests**, **Fixed Batch Size Tests**. Please refer to [OneFlow/ClickThroughRate/WideDe
已经纠正

2021-01-29 07:31 UTC, chengtbf commented on README.md
> +This section maintains the results of the special case models.
首页的ReadMe没有更新报告链接。且上面第35行的地方，介绍SpecialCases的那里最好有个list或者表格介绍每个案例的模型、对应的框架等。

2021-01-29 07:32 UTC, chengtbf commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1.md
> +# DLPerf Wide & Deep Test Report V1.0
reports路径下的首页readme里也需要有新报告的链接。

`reports/README.md`

2021-01-29 07:36 UTC, chengtbf commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1_cn.md
> +![](./imgs/wdl_vecx2_1n1g_latency.png)
这里的图我开了代理也显示不出来，路劲不对吧，没有./imgs/的文件夹。你们弄完要看一下最终网页的成品啊。

2021-01-29 07:40 UTC, chengtbf commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1_cn.md
> +3. 相同条件下 OneFlow 支持更大规模的 `batch_size` 和 `vocab_size` 。
这里的结论有点软。可以点明在某种情况下，OneFlow比HugeCTR支持词表规模大多少倍，有百分之多少的性能提升。

2021-01-29 07:44 UTC, doombeaker commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1_cn.md
> +![](./imgs/wdl_vecx2_1n1g_latency.png)
已修正

2021-01-29 07:56 UTC, chengtbf commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1_cn.md
> +![](./imgs/wdl_vecx2_4n8g_mem.png)
这个图里的图例字 WDL中的D被挡住了，处理一下。

另外对于OOM的设置，跟论文中的OOM的柱状图好像不一样。这个是经过讨论决定的吗？是不是原来OOM（latency是0，GPU memory是max）的方式更好呢？

图的横坐标，每个都有5个0，是不是太多0不太好看了。

2021-02-01 04:42 UTC, chengtbf commented on README.md
> +- [WideDeepLeaning Benchmark Test Report V1.0](./reports/WideDeepLeaning/dlperf_wide_and_deep_test_report_v1.md)
WideDeepLeaning？  少了个r，你们写完之后自己点一下链接看能不能点进去啊，这个检查不费事吧。

2021-02-01 04:48 UTC, chengtbf requested changes

2021-02-01 04:48 UTC, chengtbf commented on README.md
> +| [HugeCTR](https://github.com/NVIDIA/HugeCTR)                 | 2.2     | [samples/wdl](https://github.com/NVIDIA/HugeCTR/tree/v2.2/samples/wdl) |
这个排版不行。有两点需要改的：
- 第一点是Special Cases里分哪几个Case，你不需要一个小标题说你这个是WDL的评测吗？后面加上其他case的，如何区分呢？
- 第二点，如果要用表格做Summary，还不如列上数据，就像上面ResNet50和BERT一样，列一组4机32卡的数据。

2021-02-01 04:48 UTC, chengtbf commented on README.md
> +This section maintains the results of the special case models.
这个问题没有被解决。

2021-02-01 04:48 UTC, chengtbf commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1_cn.md
> +![](./imgs/wdl_vecx2_4n8g_mem.png)
这个问题没有被解决。

2021-02-01 04:51 UTC, chengtbf requested changes

2021-02-01 04:51 UTC, chengtbf commented on reports/README.md
> +- [WideDeepLeaning Benchmark Test Report V1.0](WideDeepLeaning/dlperf_wide_and_deep_test_report_v1.md)
拼写错误 leaning，建议全文搜索替换。

2021-02-01 04:51 UTC, chengtbf commented on reports/README.md
> +- [WideDeepLeaning 性能评测报告中文版 V1.0](WideDeepLeaning/dlperf_wide_and_deep_test_report_v1_cn.md)
拼写错误

2021-02-01 04:53 UTC, chengtbf commented
我提到的其他问题也需要解决。

2021-02-01 04:55 UTC, chengtbf commented
@doombeaker  @ouyangyu 你俩都过一下，核对一下有没有其他错误。没问题就approve

2021-02-01 04:57 UTC, Flowingsun007 commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1_cn.md
> +![](./imgs/wdl_vecx2_4n8g_mem.png)
问题已经向@ @doombeaker  @MARD1NO 反馈，图片待修改

2021-02-01 05:00 UTC, Flowingsun007 commented on README.md
> +- [WideDeepLeaning Benchmark Test Report V1.0](./reports/WideDeepLeaning/dlperf_wide_and_deep_test_report_v1.md)
已修改

2021-02-01 05:58 UTC, ouyangyu commented on HugeCTR/README.md
> +This folder holds NVIDIA HugeCTR Benchmark Test scripts, tools and reports.
这里是不是可以加下官方的参考链接地址，官方也有实现步骤。

2021-02-01 05:58 UTC, ouyangyu commented on HugeCTR/README.md
> +![latency](./imgs/hugectr_1node_1device_batchsize_double.png)
图片建议都放到oss上

2021-02-01 05:58 UTC, ouyangyu commented on HugeCTR/README.md
> +All batch size double tests were performed with 2 x 1024 Hidden Fully-connected Units.
实验步骤可以加个`./run_all.sh`，另外环境问题先应该是build.sh，如果觉得复杂可以直接贴上官网链接。另，Dockerfile文件与官方是不符的，应该是官方有更新。

2021-02-01 05:58 UTC, ouyangyu commented on HugeCTR/scripts/500_iters.sh
> +#./huge_ctr_mn --train $output_json_file >$hugectr_log_file
这个注释可以删掉？

2021-02-01 05:58 UTC, ouyangyu commented on HugeCTR/scripts/fix_total_bsz_mul_nodes_run.sh
> +#declare -a num_gpus_list=(1 )
这个也可以删掉

2021-02-01 05:58 UTC, ouyangyu commented on HugeCTR/README.md
> +    └── extract_hugectr_logs.py
这个也可以增加一个描述

2021-02-01 05:58 UTC, ouyangyu commented on OneFlow/ClickThroughRate/WideDeepLearning/README.md
> +![latency](./imgs/of_1node1Device_latency_memory.png)
图片建议放到oss上

2021-02-01 05:58 UTC, ouyangyu commented on OneFlow/ClickThroughRate/WideDeepLearning/README.md
> +|gpu|batch_size|deep_vocab_size|deep_embedding_vec_size|hidden_units_num|latency(ms)|memory_usage(MB)|
memory_usage(MB)是不是应该注明每卡内存，我看着上面单机单卡和这里的单机八卡内存一样有点迷糊。这里实际上应该取的是第0卡的内存

2021-02-01 05:58 UTC, ouyangyu commented on OneFlow/ClickThroughRate/WideDeepLearning/README.md
> +
实验步骤如果需要加的话，可以说明下Dockerfile最后一条，可安装不同指定版本oneflow，现在默认安装最新的。接着，应该先修改launch.sh里面的路劲，最后运行某个脚本，即可复现结果。

2021-02-01 05:58 UTC, ouyangyu commented on OneFlow/ClickThroughRate/WideDeepLearning/README.md
> +|gpu|batch_size|deep_vocab_size|deep_embedding_vec_size|hidden_units_num|latency(ms)|memory_usage(MB)|
hugectr也有此问题

2021-02-01 05:58 UTC, ouyangyu commented on OneFlow/ClickThroughRate/WideDeepLearning/scripts/bsz_x2.sh
> +#for repeat_id in 1 2 3 4 5
删了吧

2021-02-01 05:58 UTC, ouyangyu commented on OneFlow/ClickThroughRate/WideDeepLearning/scripts/fix_bsz.sh
> +#declare -a num_gpus_list=(8 4 2 1)
这个也可以删了

2021-02-01 05:58 UTC, ouyangyu commented on OneFlow/ClickThroughRate/WideDeepLearning/scripts/vocab_x2.sh
> +#for repeat_id in 1 2 3 4 5
这个也可以删了

2021-02-01 05:58 UTC, ouyangyu commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1_cn.md
> +Wide & Deep 是点击率预估领域非常重要的模型，被广泛应用于推荐系统。Wide & Deep 的模型非常大，并且伴随巨大的数据吞吐量，因此对深度学习框架要求很高。在很长一段时间内，在 [HugeCTR](https://github.com/NVIDIA/HugeCTR) 框架下实现的 Wide & Deep 模型性能最优。
在很长一段时间内...这一段感觉可以再修改修改想要表达的意思。

2021-02-01 05:58 UTC, ouyangyu commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1_cn.md
> +本报告中设计了一系列对比测试，旨在相同硬件条件下通过多个维度对比框架的表现和性能边界。其中，测试的维度包含词表数(`vocab_size`)、`batch_size`、GPU 数量等；框架表现的评测指标为每个迭代(iter)的耗时(latency)、GPU 显存占用大小。简单来说，latency 越小意味着性能更好，GPU 显存占用越小意味着框架对显存利用率更高、管理能力越强，且同样硬件条件下能
词表数(`vocab_size`)、`batch_size`、GPU 数量  这三个显示语法的有点不同统一

2021-02-01 06:40 UTC, doombeaker commented on HugeCTR/scripts/500_iters.sh
> +#./huge_ctr_mn --train $output_json_file >$hugectr_log_file
@ShawnXuan 脚本需要暄哥确认下，这个地方的注释是否可以删除？还有几处其它地方也有貌似多余的注释。我标注下

2021-02-01 06:49 UTC, doombeaker commented on HugeCTR/scripts/fix_total_bsz_mul_nodes_run.sh
> +    #fi
这个地方可以删除么

2021-02-01 06:50 UTC, doombeaker commented on HugeCTR/scripts/vocab_x2_1_device_run.sh
> +    #python3 $plan_generator $output_json_file
这个地方可以删除么

2021-02-01 06:58 UTC, Flowingsun007 commented on reports/README.md
> +- [WideDeepLeaning 性能评测报告中文版 V1.0](WideDeepLeaning/dlperf_wide_and_deep_test_report_v1_cn.md)
已修改

2021-02-01 06:58 UTC, Flowingsun007 commented on reports/README.md
> +- [WideDeepLeaning Benchmark Test Report V1.0](WideDeepLeaning/dlperf_wide_and_deep_test_report_v1.md)
已修改

2021-02-01 07:15 UTC, Flowingsun007 commented on README.md
> +| [HugeCTR](https://github.com/NVIDIA/HugeCTR)                 | 2.2     | [samples/wdl](https://github.com/NVIDIA/HugeCTR/tree/v2.2/samples/wdl) |
已修改

2021-02-01 07:17 UTC, Flowingsun007 commented on HugeCTR/README.md
> +All batch size double tests were performed with 2 x 1024 Hidden Fully-connected Units.
@ShawnXuan 暄哥简单加一下说明吧，还有第2行：【This folder holds NVIDIA HugeCTR Benchmark Test scripts, tools and reports.】需要加一下nvidia的链接

2021-02-01 13:31 UTC, doombeaker commented on OneFlow/ClickThroughRate/WideDeepLearning/README.md
> +
好的，这个我加一下吧

2021-02-01 13:32 UTC, doombeaker commented on OneFlow/ClickThroughRate/WideDeepLearning/README.md
> +|gpu|batch_size|deep_vocab_size|deep_embedding_vec_size|hidden_units_num|latency(ms)|memory_usage(MB)|
好的，这个我修改下

2021-02-02 01:14 UTC, doombeaker commented on HugeCTR/scripts/vocab_x2_1_device_run.sh
> +    #python3 $plan_generator $output_json_file
好像某些情况有用，还是保留吧……

2021-02-02 02:52 UTC, doombeaker commented on OneFlow/ClickThroughRate/WideDeepLearning/docker/launch.sh
> +  -v /path/to/DLPerf/OneFlow/WDL_scripts:/workspace \
DLPerf 的目录结构变了，这里的提示是不是应该改为
```
-v /path/to/DLPerf/OneFlow/ClickThroughRate/WideDeepLearning/scripts:/workspace \
```

2021-02-02 04:03 UTC, doombeaker commented on HugeCTR/README.md
> +![latency](./imgs/hugectr_1node_1device_batchsize_double.png)
整个 dlperf 的其它部分都还没有这样做，如果有需要的话，以后提一个PR一起这样做吧。
（放oss上的理由有：对国内用户速度更快；不放oss上的理由有：1. 方便整体迁移 2. 说不定以后github国内访问会变快）

2021-02-02 04:04 UTC, jackalcooper commented on HugeCTR/README.md
> +![latency](./imgs/hugectr_1node_1device_batchsize_double.png)
可以在shell脚本里面判断一下用户当前ip是中国的还是外国的

2021-02-02 04:21 UTC, doombeaker commented on HugeCTR/README.md
> +This folder holds NVIDIA HugeCTR Benchmark Test scripts, tools and reports.
已经台南佳，直接给了 HugeCTR User Guide，可否？

2021-02-02 04:23 UTC, doombeaker commented on OneFlow/ClickThroughRate/WideDeepLearning/README.md
> +
已经添加到readme最开始处

2021-02-02 04:25 UTC, doombeaker commented on OneFlow/ClickThroughRate/WideDeepLearning/README.md
> +### Run Scripts
这一节新增的关于如何使用scripts的问题，请 @ShawnXuan @ouyangyu 帮忙检查下。

2021-02-03 04:14 UTC, doombeaker commented on HugeCTR/README.md
> +All batch size double tests were performed with 2 x 1024 Hidden Fully-connected Units.
这个我加了个链接到 hugeCTR user guide了

2021-02-03 04:19 UTC, doombeaker commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1.md
> +| Framework | Version | Docker From |Model Sources|
Docker 可以去掉了，hugeCTR 的docker一直在偶尔更新，OneFlow没有提供特定的docker环境。我改下。

2021-02-03 04:21 UTC, doombeaker commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1_cn.md
> +|[HugeCTR](https://github.com/NVIDIA/HugeCTR)| 2.2 |nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04|[samples/wdl](https://github.com/NVIDIA/HugeCTR/tree/v2.2/samples/wdl)|
中文版的和英文版的docker这栏要同步（自己备忘）

2021-02-03 08:08 UTC, chengtbf commented
解决一下冲突

2021-02-03 08:16 UTC, chengtbf requested changes
拼写错误太多、太频繁了。写文档也要细心一点。实在不行用一些语法检查的网站或者拼写检查的工具。 如 ：https://app.grammarly.com/

2021-02-03 08:16 UTC, chengtbf commented on reports/WideDeepLearning/dlperf_wide_and_deep_test_report_v1_cn.md
> +|[OneFlow](https://github.com/Oneflow-Inc/oneflow/tree/v0.2.0)|0.2.0|             |[OneFolow-Benchmark](https://github.com/Oneflow-Inc/OneFlow-Benchmark/tree/v0.2.0/ClickThroughRate/WideDeepLearning)
拼写错误 OneFolow

2021-02-05 03:35 UTC, Flowingsun007 commented on README.md
> +In general, there are a lot of different implementations of these DNN models, we choose official benchmark source as well as [NVIDIA-DeepLearningExamples](https://github.com/NVIDIA/DeepLearningExampl
这块有显示问题，这段话跑到表格内部去了（应该在外面）

2021-02-05 10:25 UTC, Flowingsun007 approved these changes

2021-02-05 10:38 UTC, chengtbf approved these changes

2021-02-05 10:40 UTC, merged