Dev sx nvidia rn50
Oneflow-Inc/DLPerf pull request #56
Opened 2020-09-15 15:47 UTC by nlqq

2020-09-16 09:18 UTC, ouyangyu commented on NVIDIADeepLearningExamples/PyTorch/resnet50v1.5/scripts/run_multi_nodes.sh
> +  bash ${WORKSPACE}/scripts/single_node_train.sh ${WORKSPACE} ${DATA_DIR} ${NUM_NODES} 8 ${MASTER_NODE} ${MASTER_PORT} 128 121 $i
这里 128 --> ${bz_per_device}  121--> ${TRAIN_STEPS}

2020-09-16 09:18 UTC, ouyangyu commented on NVIDIADeepLearningExamples/PyTorch/resnet50v1.5/scripts/run_single_node.sh
> +  bash ${WORKSPACE}/scripts/single_node_train.sh ${WORKSPACE} ${DATA_DIR} ${NUM_NODES} 1 ${MASTER_NODE} ${MASTER_PORT} 128 121  $i
这里 128 --> ${bz_per_device}  121--> ${TRAIN_STEPS}

2020-09-16 09:19 UTC, ouyangyu commented on NVIDIADeepLearningExamples/PyTorch/resnet50v1.5/scripts/single_node_train.sh
> +master_port=${6:-29500}
我看到上面run_two_nodes.sh文件里这些参数都是大写，要不要统一一下

2020-09-17 06:33 UTC, chengtbf commented on NVIDIADeepLearningExamples/PyTorch/resnet50v1.5/README.md
多机跑通了，上面的介绍需要修改。

2020-09-25 07:42 UTC, nlqq commented on NVIDIADeepLearningExamples/PyTorch/resnet50v1.5/scripts/run_multi_nodes.sh
> +  bash ${WORKSPACE}/scripts/single_node_train.sh ${WORKSPACE} ${DATA_DIR} ${NUM_NODES} 8 ${MASTER_NODE} ${MASTER_PORT} 128 121 $i
ok

2020-09-25 07:42 UTC, nlqq commented on NVIDIADeepLearningExamples/PyTorch/resnet50v1.5/scripts/run_single_node.sh
> +  bash ${WORKSPACE}/scripts/single_node_train.sh ${WORKSPACE} ${DATA_DIR} ${NUM_NODES} 1 ${MASTER_NODE} ${MASTER_PORT} 128 121  $i
ok

2020-09-25 07:43 UTC, nlqq commented on NVIDIADeepLearningExamples/PyTorch/resnet50v1.5/scripts/single_node_train.sh
> +master_port=${6:-29500}
我脚本后来有更新，统一一下

2020-09-25 07:43 UTC, nlqq commented on NVIDIADeepLearningExamples/PyTorch/resnet50v1.5/README.md
ok

2020-09-27 09:07 UTC, chengtbf commented
NGC自带的容器是没法直接使用IB驱动的吧，这个PR里应该把重装IB驱动的过程也记录下来？用于其他用户复现

2020-09-27 09:09 UTC, chengtbf commented on NVIDIADeepLearningExamples/PyTorch/resnet50v1.5/README.md
> +### AMP
增加了FP16的数据，但是log文件路径和命名跟之前是一样的吗

2020-09-27 09:11 UTC, chengtbf commented on NVIDIADeepLearningExamples/PyTorch/resnet50v1.5/README.md
> +### AMP
我下载了log文件并解压，看了一下目录，应该不对吧。

2020-09-27 09:12 UTC, chengtbf requested changes
更新一下log文件下载路径

2020-10-03 02:16 UTC, chengtbf commented
review意见请及时回应和更新

2020-10-04 09:34 UTC, Flowingsun007 approved these changes

2020-10-05 01:45 UTC, chengtbf approved these changes

2020-10-05 01:50 UTC, merged